owner: yungjahja
repo: indonusa-upptime

sites:
  - name: Website Indonusa
    url: https://www.indonusa.id
  - name: Upstatus Dashboard
    url: https://upstatus.indonusa.id
  - name: Forum Indonusa
    url: https://forum.indonusa.id

status-website:
  cname: uptime.indonusa.id
  baseUrl: /
  name: Indonusa Network Status
  logoUrl: https://www.indonusa.id/logo.png
  introTitle: "**Indonusa** Service Status"
  introMessage: "Monitoring layanan publik Indonusa."
